[theme]
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[client]
showErrorDetails = true

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false

# Tắt sidebar navigation mặc định - Chúng ta tự quản lý menu bằng st.sidebar
# Xem MENU_STRUCTURE.md để biết chi tiết về cấu trúc menu
[client]
showSidebarNavigation = false