[theme]
primaryColor="#1f77b4"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f0f2f6"
textColor="#262730"
font="sans serif"

[client]
showErrorDetails = true

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false

# Tắt sidebar navigation mặc định (chúng ta sẽ tự quản lý)
# Comment out nếu muốn dùng menu tự động của Streamlit
# [client]
# showSidebarNavigation = false